config/routes.rb
Rails.application.routes.draw do
  resources :referents
  resources :tasks
  resources :folders
  resources :posts
  #resources :users
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/referent.rb
class Referent < ApplicationRecord
  has_many :tasks
end

app/controllers/referents_controller.rb
# REFERENT
class ReferentsController < ApplicationController
  before_action :set_referent, only: %i[show edit update destroy]

  # GET /referents or /referents.json
  def index
    @referents = Referent.all
  end

  # GET /referents/1 or /referents/1.json
  def show; end

  # GET /referents/new
  def new
    @referent = Referent.new
  end

  # GET /referents/1/edit
  def edit; end

  # POST /referents or /referents.json
  def create
    @referent = Referent.new(referent_params)

    respond_to do |format|
      if @referent.save
        format.html { redirect_to referent_url(@referent), notice: 'Referent was successfully created.' }
        format.json { render :show, status: :created, location: @referent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @referent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referents/1 or /referents/1.json
  def update
    respond_to do |format|
      if @referent.update(referent_params)
        format.html { redirect_to referent_url(@referent), notice: 'Referent was successfully updated.' }
        format.json { render :show, status: :ok, location: @referent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @referent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referents/1 or /referents/1.json
  def destroy
    @referent.destroy!

    respond_to do |format|
      format.html { redirect_to referents_url, notice: 'Referent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_referent
    @referent = Referent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def referent_params
    params.require(:referent).permit(:name, :email)
  end
end

app/helpers/referents_helper.rb
module ReferentsHelper
end

app/views/referents/_form.html.erb
<%= form_with(model: referent) do |form| %>
  <% if referent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(referent.errors.count, "error") %> prohibited this referent from being saved:</h2>

      <ul>
        <% referent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/referents/_referent.html.erb
<div id="<%= dom_id referent %>">
  <p>
    <strong>Name:</strong>
    <%= referent.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= referent.email %>
  </p>

</div>

app/views/referents/edit.html.erb
<h1>Editing referent</h1>

<%= render "form", referent: @referent %>

<br>

<div>
  <%= link_to "Show this referent", @referent %> |
  <%= link_to "Back to referents", referents_path %>
</div>

app/views/referents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Referents</h1>

<div id="referents">
  <% @referents.each do |referent| %>
    <%= render referent %>
    <p>
      <%= link_to "Show this referent", referent %>
    </p>
  <% end %>
</div>

<%= link_to "New referent", new_referent_path %>

app/views/referents/new.html.erb
<h1>New referent</h1>

<%= render "form", referent: @referent %>

<br>

<div>
  <%= link_to "Back to referents", referents_path %>
</div>

app/views/referents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @referent %>

<div>
  <%= link_to "Edit this referent", edit_referent_path(@referent) %> |
  <%= link_to "Back to referents", referents_path %>

  <%= button_to "Destroy this referent", @referent, method: :delete %>
</div>